### ISSUE TITLE
Let the user configure it

### ISSUE THREAD

**Issue by pedrofs** [madalinignisca/sendgrid#1]
What about documenting on how to configure the EmailTransport to use your Transport class?

This way you can remove your `bootstrap.php` completelly and let the user choose how to load `username` and `password`.

**Comment by madalinignisca** [comment]
Sure. Will update the readme as it is already possible.

BTW, how do you configure your Cake based apps, by ENV, using environments or having separate app.php?

**Comment by pedrofs** [comment]
Usually I keep separated app.php. I think the main goal here is to have credentials outside git repo.

**Comment by madalinignisca** [comment]
Yes, of course.

I have a unified app.php, no credentials ever in it.

**Comment by madalinignisca** [comment]
I've updated the Readme for how to use it where people hardcode credentials in their configs.
